import Head from 'next/head';
import dynamic from 'next/dynamic';

const Index = dynamic(() => import('@container/index'));

import { withAuth } from '@backend/middleware/withAuth';

export default function Home() {
  return (
    <div>
      <Head>
        <title>We-chat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Index />
    </div>
  );
}
export const getServerSideProps = withAuth((context) => {
  return { props: {} };
});
