import axios from 'axios';
import Head from 'next/head';
import { withAuth } from '@backend/middleware/withAuth';
import MainScreen from '../src/components/index';

export default function Home() {
  return (
    <div>
      <Head>
        <title>We-chat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainScreen />
    </div>
  );
}
export const getServerSideProps = withAuth((context) => {
  return { props: {} };
});
